"""create initial clickstream tables

Revision ID: 30d0f5f3378f
Revises: 
Create Date: 2026-08-03 20:03:50.848576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d0f5f3378f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_users_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('active_user_count', sa.Integer(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_users_metrics_window_start'), 'active_users_metrics', ['window_start'], unique=False)
    op.create_table('events_raw',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('page_url', sa.String(), nullable=False),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_raw_session_id'), 'events_raw', ['session_id'], unique=False)
    op.create_index(op.f('ix_events_raw_user_id'), 'events_raw', ['user_id'], unique=False)
    op.create_table('funnel_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_metrics_window_start'), 'funnel_metrics', ['window_start'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('entry_page', sa.String(), nullable=False),
    sa.Column('exit_page', sa.String(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('reached_checkout', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_funnel_metrics_window_start'), table_name='funnel_metrics')
    op.drop_table('funnel_metrics')
    op.drop_index(op.f('ix_events_raw_user_id'), table_name='events_raw')
    op.drop_index(op.f('ix_events_raw_session_id'), table_name='events_raw')
    op.drop_table('events_raw')
    op.drop_index(op.f('ix_active_users_metrics_window_start'), table_name='active_users_metrics')
    op.drop_table('active_users_metrics')
    # ### end Alembic commands ###
