"""add last_processed_event_id to sessions

Revision ID: 8d68bab35de5
Revises: 30d0f5f3378f
Create Date: 2026-08-05 17:45:16.570217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d68bab35de5'
down_revision: Union[str, Sequence[str], None] = '30d0f5f3378f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_processed_event_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_processed_event_id')
    # ### end Alembic commands ###
